dist: bionic
language: csharp
solution: MediatR.Extensions.Autofac.DependencyInjection.sln
mono: none
dotnet: 6.0.100

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

addons:
  apt:
    update: true

stages:
  - build
  - test
  - publish
jobs:
  include:
    - stage: build
      name: dotnet build
      script: dotnet build
    - stage: test
      name: dotnet test
      before_script:
        - sudo apt-get update && sudo apt-get install curl -y
      script: ./test.sh
    - stage: publish
      name: publish-packages
      if: tag IS present
      script: ./publish-packages.sh "$NUGET_SOURCE" "$NUGET_KEY" "$TRAVIS_TAG"