dist: bionic
language: csharp
solution: MediatR.Extensions.Autofac.DependencyInjection.sln
mono: none
dotnet: 3.1.100
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
stages:
  - build
  - test
  - publish
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
    - stage: test
      name: run-tests
      script: ./run-tests.sh
    - stage: publish
      name: publish-packages
      if: tag IS present
      script: ./publish-packages.sh "$NUGET_SOURCE" "$CLEANCODELABS_NUGET_KEY" "$TRAVIS_TAG"

